version: 2.1

executors:
  basic:
    docker:
      - image: cimg/python:3.9
    resource_class: small

jobs:
  test:
    parameters:
      working-directory:
        type: string
    executor: basic
    working_directory: << parameters.working-directory >>
    steps:
      - checkout:
          path: ~/project
      - run: |
          pwd
          ls -laH .
      - run:
          name: run script in working directory
          command: python test.py
          environment:
            FOO: "fun with working directory"
            BAR: "good times with working directory"
      - run:
          name: generate new file
          command: |
            echo "Ran from ${CIRCLE_BUILD_URL}" > $CIRCLE_JOB.txt

            cat $CIRCLE_JOB.txt
      - persist_to_workspace:
          # current working directory
          root: .
          paths:
            - *.txt
  check:
    executor: basic
    steps:
      - attach_workspace:
          at: ~/project
      - run: ls -laH .

workflows:
  main:
    jobs:
      - test:
          name: foo
          working-directory: ~/project/foo
      - test:
          name: bar
          working-directory: ~/project/bar
      - check:
          requires:
            - foo
            - bar
