version: 2.1

jobs:
  build:
    parameters:
      after-deps:
        description: "Steps that will be executed after dependencies are installed, but before tests are run"
        type: steps
        default:
          - run: |
              echo "No steps provided"
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - run: |
          echo "<< parameters.after-deps >>"
      - steps: << parameters.after-deps >>

            
workflows:
  workflow:
    jobs:
      - build:
          name: no-custom-steps
      - build:
          name: with-custom-steps
          after-deps:
            - run: echo custom
