version: 2.1

executors:
  basic:
    docker:
      - image: cimg/python:3.9
    resource_class: small

jobs:
  test:
    parameters:
      working-directory:
        description: relative folder to ~/project
        type: string
    executor: basic
    working_directory: ~/project/<< parameters.working-directory >>
    steps:
      - checkout:
          path: ~/project
      - run: |
          pwd
          ls -laH .
      - run:
          name: run script in working directory
          command: python test.py
          environment:
            FOO: "fun with working directory"
            BAR: "good times with working directory"
      - run:
          name: generate new file
          command: |
            echo "Ran from ${CIRCLE_BUILD_URL}" > $CIRCLE_JOB.txt

            cat $CIRCLE_JOB.txt
      - persist_to_workspace:
          # current working directory
          root: ~/project
          paths:
            # try to persist everything in the working directory
            - << parameters.working-directory >>
  check:
    executor: basic
    steps:
      - attach_workspace:
          at: ~/project
      - run: sudo apt install tree
      - run: |
          tree -L 3 .

workflows:
  main:
    jobs:
      - test:
          name: foo
          working-directory: foo
      - test:
          name: bar
          working-directory: bar
      - check:
          requires:
            - foo
            - bar
