version: 2.1

jobs:
  build:
    parameters:
      after-deps:
        description: "Steps that will be executed after dependencies are installed, but before tests are run"
        type: steps
        default: []
    docker:
      - image: cimg/base:edge
    steps:
      - checkout
      - run: echo "<< parameters.after-deps >>"
      - when:
          condition: << parameters.after-deps >>
          steps:
            - steps: << parameters.after-deps >>
      - unless:
          condition: << parameters.after-deps >>
          steps:
            - run: echo "No steps provided"
            
workflows:
  workflow:
    jobs:
      - build:
          name: no-custom-steps
      - build:
          name: with-custom-steps
          after-deps:
            - run: echo custom
